"""
HydroMet-ETL
Week 11 — Orchestration Tests

These tests validate the orchestration metadata generated by
a successful pipeline execution.

The tests intentionally do not execute the entire pipeline
again because database loading is comparatively expensive.
Instead, they validate the recorded orchestration evidence.
"""

from pathlib import Path
import json


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RUN_SUMMARY_PATH = (
    PROJECT_ROOT
    / "outputs"
    / "orchestration"
    / "pipeline_run_summary.json"
)

LOG_DIR = (
    PROJECT_ROOT
    / "logs"
    / "orchestration"
)


def load_summary():

    with open(
        RUN_SUMMARY_PATH,
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(file)


def test_pipeline_run_summary_exists():

    assert RUN_SUMMARY_PATH.exists()


def test_pipeline_status_success():

    summary = load_summary()

    assert summary["status"] == "SUCCESS"


def test_ingestion_was_intentionally_skipped():

    summary = load_summary()

    assert summary["skip_ingestion"] is True


def test_six_stages_executed():

    summary = load_summary()

    assert len(summary["stages"]) == 6


def test_expected_stage_order():

    summary = load_summary()

    actual = [
        stage["stage"]
        for stage in summary["stages"]
    ]

    expected = [
        "data_quality",
        "database_schema",
        "database_load",
        "serving_layer",
        "ml_preparation",
        "regression_tests",
    ]

    assert actual == expected


def test_all_executed_stages_successful():

    summary = load_summary()

    assert all(
        stage["status"] == "SUCCESS"
        for stage in summary["stages"]
    )


def test_all_stage_return_codes_zero():

    summary = load_summary()

    assert all(
        stage["return_code"] == 0
        for stage in summary["stages"]
    )


def test_pipeline_duration_recorded():

    summary = load_summary()

    assert summary["duration_seconds"] > 0


def test_stage_durations_recorded():

    summary = load_summary()

    assert all(
        stage["duration_seconds"] > 0
        for stage in summary["stages"]
    )


def test_stage_logs_exist():

    summary = load_summary()

    for stage in summary["stages"]:

        log_path = (
            PROJECT_ROOT
            / stage["log_file"]
        )

        assert log_path.exists()


def test_database_load_was_recorded():

    summary = load_summary()

    stages = {
        stage["stage"]: stage
        for stage in summary["stages"]
    }

    assert "database_load" in stages

    assert (
        stages["database_load"][
            "duration_seconds"
        ]
        > 0
    )